quarto::quarto_render(
  input = "Biggie.qmd",
  execute_params = list(
    patient = "Biggie",
    first_name = "Biggie",
    last_name = "Smalls",
    mrn = 000000000,
    dob = "1999-01-01",
    doe1 = "2023-01-01",
    doe2 = "2023-01-01",
    doe3 = "2023-01-01",
    sex = "male",
    sex_cap = "Male",
    age = 22,
    education = 15,
    handedness = "right",
    referral = "Dr. Dre",
    observer = "Mrs. Wallace",
    observer_relation = "mother",
    he_she = "he",
    he_she_cap = "He",
    his_her = "his",
    his_her_cap = "His",
    him_her = "him",
    him_her_cap = "Him",
    dx1 = "attention-deficit/hyperactivity disorder (ADHD)",
    dx2 = "anxiety",
    dx3 = "depression"
  ),
  output_file = "Biggie.pdf"
)
