params:
  last_name: Smalls
  first_name: Biggie
  mrn: NULL
  dob: 1995-01-01
  doe1: 2023-04-01
  doe2: 2023-04-02
  doe3: 2023-04-03
  sex: female
  sex_cap: Female
  age: 28
  educyrs: 16
  he_she: she
  he_she_cap: She
  his_her: her
  his_her_cap: Her
  him_her: her
  him_her_cap: Her
