filter_executive <- c(
  "NAB Attention Index",
  "Digits Forward",
  "Digits Forward Longest Span",
  "Digits Backward",
  "Digits Backward Longest Span",
  "Dots",
  "Numbers & Letters Part A Efficiency",
  "Numbers & Letters Part B Efficiency",
  "Numbers & Letters Part C Efficiency",
  "Numbers & Letters Part D Efficiency",
  "Driving Scenes",
  "NAB Executive Functions Index",
  "Mazes",
  "Categories",
  "Word Generation",
  "Word Generation Perseverations",
  "Judgment",
  "Working Memory (WMI)",
  "Arithmetic",
  "Digit Span",
  "Longest Digit Span Forward",
  "Longest Digit Span Backward",
  "Longest Digit Span Sequence",
  "Letter-Number Sequencing",
  "Symbol Span",
  "Spatial Span",
  "Picture Span",
  "Processing Speed (PSI)",
  "Coding",
  "Cancellation",
  "Symbol Search",
  "TMT, Part A",
  "TMT, Part B",
  "Unstructured Task",
  "Attention Index"
)
